// PPL Training Requirements based on FAA FAR 61.109
// All training tasks with FAA regulation references

import type { TrainingTask, TaskCategory } from '../types';

export const PPL_REQUIREMENTS = {
    totalHours: 40,
    soloHours: 10,
    crossCountryHours: 3,
    nightHours: 3,
    instrumentHours: 3,
    groundSchoolTopics: 8,
};

export const TRAINING_TASKS: Omit<TrainingTask, 'id'>[] = [
    // Ground School
    {
        category: 'ground_school',
        title: 'Aerodynamics & Principles of Flight',
        description: 'Understand lift, drag, thrust, weight, and how they affect aircraft performance.',
        estimated_hours: 4,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.105(b)(1)',
    },
    {
        category: 'ground_school',
        title: 'Aircraft Systems',
        description: 'Learn about engine, electrical, fuel, and flight control systems.',
        estimated_hours: 3,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.105(b)(2)',
    },
    {
        category: 'ground_school',
        title: 'Weather Theory & Reports',
        description: 'Interpret METARs, TAFs, and understand weather patterns affecting flight.',
        estimated_hours: 5,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.105(b)(5)',
    },
    {
        category: 'ground_school',
        title: 'Navigation & Flight Planning',
        description: 'VFR navigation techniques, chart reading, and flight computer use.',
        estimated_hours: 4,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.105(b)(7)',
    },
    {
        category: 'ground_school',
        title: 'Federal Aviation Regulations',
        description: 'Part 61, 91, and related regulations for private pilots.',
        estimated_hours: 4,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.105(b)(8)',
    },
    {
        category: 'ground_school',
        title: 'Aeromedical Factors',
        description: 'Hypoxia, spatial disorientation, and physiological factors.',
        estimated_hours: 2,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.105(b)(9)',
    },
    {
        category: 'ground_school',
        title: 'Airspace & ATC Procedures',
        description: 'Understanding airspace classes, communication, and ATC.',
        estimated_hours: 3,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.105(b)(10)',
    },
    {
        category: 'ground_school',
        title: 'Airport Operations',
        description: 'Taxiing, runway markings, lighting, and traffic patterns.',
        estimated_hours: 2,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.105(b)(11)',
    },

    // Flight Training
    {
        category: 'flight',
        title: 'Pre-flight Procedures',
        description: 'Aircraft inspection, weight & balance, and preflight planning.',
        estimated_hours: 1,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.107(b)(1)',
    },
    {
        category: 'flight',
        title: 'Takeoffs & Landings',
        description: 'Normal, crosswind, short field, and soft field takeoffs/landings.',
        estimated_hours: 8,
        prerequisites: ['Pre-flight Procedures'],
        certification_level: 'private',
        far_reference: 'FAR 61.109(a)(2)',
    },
    {
        category: 'flight',
        title: 'Basic Maneuvers',
        description: 'Straight and level, climbs, descents, turns, and stalls.',
        estimated_hours: 5,
        prerequisites: ['Pre-flight Procedures'],
        certification_level: 'private',
        far_reference: 'FAR 61.107(b)(3)',
    },
    {
        category: 'flight',
        title: 'Slow Flight & Stalls',
        description: 'Power-on stalls, power-off stalls, and slow flight practice.',
        estimated_hours: 3,
        prerequisites: ['Basic Maneuvers'],
        certification_level: 'private',
        far_reference: 'FAR 61.107(b)(4)',
    },
    {
        category: 'flight',
        title: 'Ground Reference Maneuvers',
        description: 'S-turns, turns around a point, rectangular course.',
        estimated_hours: 3,
        prerequisites: ['Basic Maneuvers'],
        certification_level: 'private',
        far_reference: 'FAR 61.107(b)(5)',
    },
    {
        category: 'flight',
        title: 'Emergency Procedures',
        description: 'Engine failures, emergency landings, and system malfunctions.',
        estimated_hours: 2,
        prerequisites: ['Basic Maneuvers'],
        certification_level: 'private',
        far_reference: 'FAR 61.107(b)(11)',
    },
    {
        category: 'flight',
        title: 'Night Flying',
        description: 'Night takeoffs, landings, and navigation (3 hours required).',
        estimated_hours: 3,
        prerequisites: ['Takeoffs & Landings'],
        certification_level: 'private',
        far_reference: 'FAR 61.109(a)(2)',
    },
    {
        category: 'flight',
        title: 'Cross-Country Flight',
        description: 'Navigation flights over 50nm with landings at other airports.',
        estimated_hours: 5,
        prerequisites: ['Navigation & Flight Planning', 'Takeoffs & Landings'],
        certification_level: 'private',
        far_reference: 'FAR 61.109(a)(5)',
    },
    {
        category: 'flight',
        title: 'Solo Practice',
        description: 'Solo practice of maneuvers and cross-country (10 hours required).',
        estimated_hours: 10,
        prerequisites: ['Basic Maneuvers', 'Takeoffs & Landings'],
        certification_level: 'private',
        far_reference: 'FAR 61.109(a)(5)',
    },

    // Simulator Training
    {
        category: 'simulator',
        title: 'Basic Instrument Flying',
        description: 'Instrument reference to straight and level, turns, climbs, descents.',
        estimated_hours: 3,
        prerequisites: ['Basic Maneuvers'],
        certification_level: 'private',
        far_reference: 'FAR 61.109(a)(3)',
    },

    // Exam Prep
    {
        category: 'exam',
        title: 'FAA Knowledge Test Prep',
        description: 'Study and practice for the FAA Private Pilot written exam.',
        estimated_hours: 20,
        prerequisites: [],
        certification_level: 'private',
        far_reference: 'FAR 61.103(d)',
    },
    {
        category: 'exam',
        title: 'Oral Exam Preparation',
        description: 'Prepare for the oral portion of the practical test.',
        estimated_hours: 5,
        prerequisites: ['FAA Knowledge Test Prep'],
        certification_level: 'private',
        far_reference: 'FAR 61.103(f)',
    },
    {
        category: 'exam',
        title: 'Checkride Preparation',
        description: 'Review all maneuvers and procedures for the practical test.',
        estimated_hours: 5,
        prerequisites: ['Oral Exam Preparation'],
        certification_level: 'private',
        far_reference: 'FAR 61.103(f)',
    },
];

export const CATEGORY_LABELS: Record<TaskCategory, { label: string; emoji: string }> = {
    ground_school: { label: 'Ground School', emoji: '📚' },
    flight: { label: 'Flight Training', emoji: '✈️' },
    simulator: { label: 'Simulator', emoji: '🖥️' },
    exam: { label: 'Exam Prep', emoji: '📝' },
};
